CREATE TABLE Users (
                       Username VARCHAR2(25 CHAR) PRIMARY KEY,
                       Password VARCHAR2(25 CHAR) NOT NULL
);


INSERT INTO USERS (Username, Password) values ('abdel', 'gad');
INSERT INTO USERS (Username, Password) values ('dzz', 'zd');

SELECT * FROM Users;

SELECT Username, Password FROM Users Where Username ='abdel' AND Password='gad';

-------------------------------

DROP TABLE Defis;
CREATE TABLE Defis(
                      Nom VARCHAR2(25 CHAR) PRIMARY KEY,
                      NbOperations INTEGER NOT NULL,
                      Domain1Min Integer NOT NULL,
                      Domain1Max Integer NOT NULL,
                      Domain2Min Integer NOT NULL,
                      Domain2Max Integer NOT NULL,
                      RefUser VARCHAR2(25 CHAR) REFERENCES Users(Username)
);

INSERT INTO DEFIS VALUES ('FirstDefi', 5, 1, 2,3,4,'abdel');

-------------------------------
DROP TABLE Scores;

CREATE TABLE Scores(
                       NumScore Integer GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       Temps Number NOT NULL,
                       NBErreurs Integer NOT NULL,
                       ScoreDate Date NOT NULL,
                       RefDefi VARCHAR2(25 CHAR) REFERENCES Defis(Nom)
);

INSERT INTO Scores (Temps, NBErreurs, ScoreDate, RefDefi) VALUES (100.4 , 1, to_date('04/04/1975', 'dd/mm/yyyy'),'defi2');

commit;